### ISSUE TITLE
undefined reference to "main"

### ISSUE THREAD

**Issue by thecowmilk** [devershichandra27/C-implementation-of-AES#3]
```
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/Scrt1.o: in function `_start':
(.text+0x24): undefined reference to `main'
collect2: error: ld returned 1 exit status
```
how to fix? thanks

**Comment by devershichandra27** [comment]
Hi! You need to call the encryption and decryption function by creating your own main function. the plaintext itself will be converted to the cipher text later. I have updated the readme.
